#-----------------------------------------------------------------------

APP       := ServerEngine
TARGET    := DALComm
CONFIG    := 
STRIP_FLAG:= N
INCLUDE   :=
LIB       :=
LOCAL_SRC :=

#-----------------------------------------------------------------------
include /home/mage/Desktop/servercode/tool/taf/taf/makefile.taf
#-----------------------------------------------------------------------
