// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.0 by WSRD Tencent.
// Generated from `FrontServer.jce'
// **********************************************************************

package com.qq.Oss;

public final class OssFrontPrxHelper extends com.qq.taf.proxy.ServantProxy implements OssFrontPrx
{

    public OssFrontPrxHelper taf_hash(int hashCode)
    {
        super.taf_hash(hashCode);
        return this;
    }

    public java.util.Map __defaultContext()
    {
        java.util.HashMap _ctx = new java.util.HashMap();
        return _ctx;
    }

    protected String sServerEncoding = "GBK";
    public int setServerEncoding(String se){
        sServerEncoding = se;
        return 0;
    }

    public int doOssRequest(String strReq, com.qq.taf.holder.JceStringHolder strRetData)
    {
        return doOssRequest(strReq, strRetData, __defaultContext());
    }

    @SuppressWarnings("unchecked")
    public int doOssRequest(String strReq, com.qq.taf.holder.JceStringHolder strRetData, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(strReq, 1);
        if(strRetData.value != null)         _os.write(strRetData.value, 2);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> _mStatus = new java.util.HashMap<String, String>();

        byte[] _returnSBuffer = taf_invoke("doOssRequest", _sBuffer, __ctx, _mStatus);

        com.qq.taf.jce.JceInputStream _is = new com.qq.taf.jce.JceInputStream(_returnSBuffer);
        _is.setServerEncoding(sServerEncoding);
        int _ret = 0;
        _ret = (int) _is.read(_ret, 0, true);
        strRetData.value = "";
        strRetData.value = (String) _is.read(strRetData.value, 2, true);
        return _ret;
    }

    public void async_doOssRequest(com.qq.Oss.OssFrontPrxCallback callback, String strReq)
    {
        async_doOssRequest(callback, strReq, __defaultContext());
    }

    public void async_doOssRequest(com.qq.Oss.OssFrontPrxCallback callback, String strReq, java.util.Map __ctx)
    {
        com.qq.taf.jce.JceOutputStream _os = new com.qq.taf.jce.JceOutputStream(0);
        _os.setServerEncoding(sServerEncoding);
        _os.write(strReq, 1);
        byte[] _sBuffer = com.qq.taf.jce.JceUtil.getJceBufArray(_os.getByteBuffer());

        java.util.HashMap<String, String> _mStatus = new java.util.HashMap<String, String>();

        taf_invokeAsync(callback, "doOssRequest", _sBuffer, __ctx, _mStatus);

    }

}
