// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.0 by WSRD Tencent.
// Generated from `FrontServer.jce'
// **********************************************************************

package com.qq.Oss;

public interface OssFrontPrx
{
    public int doOssRequest(String strReq, com.qq.taf.holder.JceStringHolder strRetData);

    public int doOssRequest(String strReq, com.qq.taf.holder.JceStringHolder strRetData, java.util.Map __ctx);

    public void async_doOssRequest(com.qq.Oss.OssFrontPrxCallback callback, String strReq);

    public void async_doOssRequest(com.qq.Oss.OssFrontPrxCallback callback, String strReq, java.util.Map __ctx);


}
