#ifndef __FIGHTSOUL_PROPERTY_H__
#define __FIGHTSOUL_PROPERTY_H__

#include "PropertyComm.h"


PROP_DEFBEGIN()

	PROP_DEFIMP(PROP_FIGHTSOUL_ATT, int, 1, "攻击")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_MAXHP, int, "生命")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_HIT, int, "命中")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_DOGE, int, "闪避")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_BLOCK, int, "抵挡")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_WRECK, int, "破击")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_KNOCK, int, "暴击")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_ANTIKNOCK, int, "韧性")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_ARMOR, int, "护甲")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_SUNDER, int, "破甲")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_ANGER, int, "怒气")
	PROP_SIMPLEDEFIMP(PROP_FIGHTSOUL_EXP, int, "经验")
	
PROP_DEFEND()


#endif
