// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.0 by WSRD Tencent.
// Generated from `GMOnline.jce'
// **********************************************************************

#ifndef __GMONLINE_H_
#define __GMONLINE_H_

#include <map>
#include <string>
#include <vector>
#include "jce/Jce.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"


namespace ServerEngine
{

    /* callback of async proxy for client */
    class GMOnlinePrxCallback: public taf::ServantProxyCallback
    {
    public:
        virtual ~GMOnlinePrxCallback(){}
    public:
        int onDispatch(taf::ReqMessagePtr msg);
    };
    typedef taf::TC_AutoPtr<GMOnlinePrxCallback> GMOnlinePrxCallbackPtr;

    /* proxy for client */
    class GMOnlineProxy : public taf::ServantProxy
    {
    public:
        typedef map<string, string> TAF_CONTEXT;
        GMOnlineProxy* taf_hash(int64_t key);
    };
    typedef taf::TC_AutoPtr<GMOnlineProxy> GMOnlinePrx;

    /* servant for server */
    class GMOnline : public taf::Servant
    {
    public:
        virtual ~GMOnline(){}
    public:
        int onDispatch(taf::JceCurrentPtr _current, vector<char> &_sResponseBuffer);
    };


}



#endif
