#-----------------------------------------------------------------------

APP       := ServerEngine
TARGET    := DALComm
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   :=

LIB       :=

LOCAL_SRC :=

RELEASE_JCE += DbPool.h MultiDbPool.h DalDbInterface.h

#-----------------------------------------------------------------------
include /home/mage/Desktop/servercode/tool/taf/taf/makefile.taf
#-----------------------------------------------------------------------
