#-----------------------------------------------------------------------

APP       := ServerEngine
TARGET    :=
CONFIG    := 
STRIP_FLAG:= N
INCLUDE   := -I../../../Common/CommJce/ -I../../Cluster/OssServer/
LIB       :=
LOCAL_SRC :=

#-----------------------------------------------------------------------
include /home/mage/Desktop/servercode/src/ServerEngine/DALComm/DALComm.mk
include /home/mage/Desktop/servercode/tool/taf/taf/makefile.taf
#-----------------------------------------------------------------------
